# Color Class

In [1]:
class colors: 
    reset='\033[0m'
    bold='\033[01m'
    disable='\033[02m'
    underline='\033[04m'
    reverse='\033[07m'
    strikethrough='\033[09m'
    invisible='\033[08m'
    class fg: 
        black='\033[30m'
        red='\033[31m'
        green='\033[32m'
        orange='\033[33m'
        blue='\033[34m'
        purple='\033[35m'
        cyan='\033[36m'
        lightgrey='\033[37m'
        darkgrey='\033[90m'
        lightred='\033[91m'
        lightgreen='\033[92m'
        yellow='\033[93m'
        lightblue='\033[94m'
        pink='\033[95m'
        lightcyan='\033[96m'
    class bg: 
        black='\033[40m'
        red='\033[41m'
        green='\033[42m'
        orange='\033[43m'
        blue='\033[44m'
        purple='\033[45m'
        cyan='\033[46m'
        lightgrey='\033[47m'

In [2]:
print(colors.bg.green, "SKk", colors.fg.red, "Amartya") 
print(colors.bg.lightgrey, "SKk", colors.fg.red, "Amartya") 

 SKk  Amartya
 SKk  Amartya


# Chapter 3 Starts here

In [3]:
import numpy as np 

In [4]:
A = np.random.randint(1,13,(5,5)); 
print(A , "\n") 
print(A.shape , "\n") 

[[ 5  6  4  8 12]
 [12  4 11  2  7]
 [ 8  4 12  3  8]
 [ 3  8  6 11  4]
 [ 5  3 11  8  1]] 

(5, 5) 



# Row of Matrix

In [5]:
print('{}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[0,0],A[0,1],A[0,2],A[0,3],A[0,4],colors.reset));
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[1,0],A[1,1],A[1,2],A[0,3],A[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[2,0],A[2,1],A[2,2],A[0,3],A[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[3,0],A[3,1],A[3,2],A[0,3],A[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[4,0],A[4,1],A[4,2],A[0,3],A[4,4]))

 5  6  4  8 12
12  4 11  8  7
 8  4 12  8  8
 3  8  6  8  4
 5  3 11  8  1


# Column of Matrix

In [6]:
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(colors.fg.blue,A[0,0],colors.reset,A[0,1],A[0,2],A[0,3],A[0,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(colors.fg.blue,A[1,0],colors.reset,A[1,1],A[1,2],A[0,3],A[1,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(colors.fg.blue,A[2,0],colors.reset,A[2,1],A[2,2],A[0,3],A[2,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(colors.fg.blue,A[3,0],colors.reset,A[3,1],A[3,2],A[0,3],A[3,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(colors.fg.blue,A[4,0],colors.reset,A[4,1],A[4,2],A[0,3],A[4,4]))

 5  6  4  8 12
12  4 11  8  7
 8  4 12  8  8
 3  8  6  8  4
 5  3 11  8  1


# Vector(A[Row]) * Vector(B[Col]) = C(#rowA,#colB)
1st Way: Regular Way

In [7]:
A = np.random.randint(1,13,(5,5));
B = np.random.randint(1,13,(5,5));

## Matrix A

In [8]:
print('A = \n')
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[0,0],A[0,1],A[0,2],A[0,3],A[0,4]));
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[1,0],A[1,1],A[1,2],A[0,3],A[1,4]))
print('{}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[2,0],A[2,1],A[2,2],A[0,3],A[2,4],colors.reset))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[3,0],A[3,1],A[3,2],A[0,3],A[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[4,0],A[4,1],A[4,2],A[0,3],A[4,4]))
print('\n')
print('A(row 3) = {}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[2,0],A[2,1],A[2,2],A[0,3],A[2,4],colors.reset))
As = 'A(row 3) = {}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[2,0],A[2,1],A[2,2],A[0,3],A[2,4],colors.reset);


A = 

 8 10  8  2  2
 4  6  9  2  6
 8  4  4  2  7
 9  3  8  2  1
 7  3  3  2  6


A(row 3) =  8  4  4  2  7


## Matrix B

In [9]:
print('B = \n')
clr1 = colors.fg.blue; 
clr2 = colors.reset; 

print('{:2d} {:2d} {:2d} {}{:2d}{} {:2d}'.format(B[0,0],B[0,1],B[0,2],clr1,B[0,3],clr2,B[0,4]))
print('{:2d} {:2d} {:2d} {}{:2d}{} {:2d}'.format(B[1,0],B[1,1],B[1,2],clr1,B[1,3],clr2,B[1,4]))
print('{:2d} {:2d} {:2d} {}{:2d}{} {:2d}'.format(B[2,0],B[2,1],B[2,2],clr1,B[2,3],clr2,B[2,4]))
print('{:2d} {:2d} {:2d} {}{:2d}{} {:2d}'.format(B[3,0],B[3,1],B[3,2],clr1,B[3,3],clr2,B[3,4]))
print('{:2d} {:2d} {:2d} {}{:2d}{} {:2d}'.format(B[4,0],B[4,1],B[4,2],clr1,B[4,3],clr2,B[4,4]))
print('\n')
print('B(col 4) =\n{}{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}{}'.format(colors.fg.blue,B[0,3],B[1,3],B[2,3],B[3,3],B[4,3],colors.reset))
Bs = 'B(col 4) =\n{}{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}{}'.format(colors.fg.blue,B[0,3],B[1,3],B[2,3],B[3,3],B[4,3],colors.reset);

B = 

 3 10 10  4 10
 2  4 11  4  9
 7 11 11  3 10
 3  7 12  6 11
 9 11  9  8  6


B(col 4) =
 4
 4
 3
 6
 8


## C[3,4]

In [10]:
print(As ,'\n*\n',Bs)
C = np.dot(A[2,:],B[:,3]);
print("\nC[3,4]: " ,C , "\n\n")

C = np.dot(A,B);
print(C)

A(row 3) =  8  4  4  2  7 
*
 B(col 4) =
 4
 4
 3
 6
 8

C[3,4]:  158 


[[124 244 320 124 284]
 [150 250 295 133 253]
 [144 266 315 158 275]
 [110 229 268 104 247]
 [120 223 262 133 229]]


# Matrix(A) * Vector(B[Col]) = C Matrix
Columns of 'C' are combinations of Columns of 'A'

2nd Way: Column Way

## Matrix A

In [11]:
print('A =')
print(colors.fg.red)
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[0,0],A[0,1],A[0,2],A[0,3],A[0,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[1,0],A[1,1],A[1,2],A[0,3],A[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[2,0],A[2,1],A[2,2],A[0,3],A[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[3,0],A[3,1],A[3,2],A[0,3],A[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[4,0],A[4,1],A[4,2],A[0,3],A[4,4]))


A =

 8 10  8  2  2
 4  6  9  2  6
 8  4  4  2  7
 9  3  8  2  1
 7  3  3  2  6


## Matrix B

In [12]:
print('B = \n')
clr1 = colors.fg.blue; 
clr2 = colors.reset; 

print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(clr1,B[0,0],clr2,B[0,1],B[0,2],B[0,3],B[0,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(clr1,B[1,0],clr2,B[1,1],B[1,2],B[1,3],B[1,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(clr1,B[2,0],clr2,B[2,1],B[2,2],B[2,3],B[2,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(clr1,B[3,0],clr2,B[3,1],B[3,2],B[3,3],B[3,4]))
print('{}{:2d}{} {:2d} {:2d} {:2d} {:2d}'.format(clr1,B[4,0],clr2,B[4,1],B[4,2],B[4,3],B[4,4]))
print('\n')
print('{:2d} {}{:2d}{} {:2d} {:2d} {:2d}'.format(B[0,0],clr1,B[0,1],clr2,B[0,2],B[0,3],B[0,4]))
print('{:2d} {}{:2d}{} {:2d} {:2d} {:2d}'.format(B[1,0],clr1,B[1,1],clr2,B[1,2],B[1,3],B[1,4]))
print('{:2d} {}{:2d}{} {:2d} {:2d} {:2d}'.format(B[2,0],clr1,B[2,1],clr2,B[2,2],B[2,3],B[2,4]))
print('{:2d} {}{:2d}{} {:2d} {:2d} {:2d}'.format(B[3,0],clr1,B[3,1],clr2,B[3,2],B[3,3],B[3,4]))
print('{:2d} {}{:2d}{} {:2d} {:2d} {:2d}'.format(B[4,0],clr1,B[4,1],clr2,B[4,2],B[4,3],B[4,4]))
print('\n.\n.')

B = 

 3 10 10  4 10
 2  4 11  4  9
 7 11 11  3 10
 3  7 12  6 11
 9 11  9  8  6


 3 10 10  4 10
 2  4 11  4  9
 7 11 11  3 10
 3  7 12  6 11
 9 11  9  8  6

.
.


## Matrix C

In [13]:
C1 = np.dot(A,B[:,0]);
C2 = np.dot(A,B[:,1]);
C3 = np.dot(A,B[:,2]);
C4 = np.dot(A,B[:,3]);
C5 = np.dot(A,B[:,4]);

print("C[:,0]:");
print(colors.fg.purple);
print('{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}'.format(C1[0],C1[1],C1[2],C1[3],C1[4]));
print(colors.reset);

print("C[:,1]:");
print(colors.fg.purple);
print('{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}'.format(C2[0],C2[1],C2[2],C1[3],C2[4]));
print(colors.reset);

print("C[:,2]:");
print(colors.fg.purple);
print('{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}'.format(C3[0],C3[1],C3[2],C3[3],C3[4]));
print(colors.reset);

print("C[:,3]:");
print(colors.fg.purple);
print('{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}'.format(C4[0],C4[1],C4[2],C4[3],C4[4]));
print(colors.reset);

print("C[:,4]:");
print(colors.fg.purple);
print('{:2d}\n{:2d}\n{:2d}\n{:2d}\n{:2d}'.format(C5[0],C5[1],C5[2],C5[3],C5[4]));
print(colors.reset);

print('C =')
print(colors.fg.purple)
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[0,0],C[0,1],C[0,2],C[0,3],C[0,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[1,0],C[1,1],C[1,2],C[0,3],C[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[2,0],C[2,1],C[2,2],C[0,3],C[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[3,0],C[3,1],C[3,2],C[0,3],C[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[4,0],C[4,1],C[4,2],C[0,3],C[4,4]))

C[:,0]:

124
150
144
110
120

C[:,1]:

244
250
266
110
223

C[:,2]:

320
295
315
268
262

C[:,3]:

124
133
158
104
133

C[:,4]:

284
253
275
247
229

C =

124 244 320 124 284
150 250 295 124 253
144 266 315 124 275
110 229 268 124 247
120 223 262 124 229


# Vector(A[Row]) * Matrix(B) = C Matrix
Rows of 'C' are combinations of Row 'B'

3rd Way: Row Way


## Matrix A

In [14]:
print('A = \n')
print('{}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[0,0],A[0,1],A[0,2],A[0,3],A[0,4],colors.reset));
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[1,0],A[1,1],A[1,2],A[0,3],A[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[2,0],A[2,1],A[2,2],A[0,3],A[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[3,0],A[3,1],A[3,2],A[0,3],A[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[4,0],A[4,1],A[4,2],A[0,3],A[4,4]))
print('\n')
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[0,0],A[0,1],A[0,2],A[0,3],A[0,4],));
print('{}{:2d} {:2d} {:2d} {:2d} {:2d}{}'.format(colors.fg.red,A[1,0],A[1,1],A[1,2],A[0,3],A[1,4],colors.reset))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[2,0],A[2,1],A[2,2],A[0,3],A[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[3,0],A[3,1],A[3,2],A[0,3],A[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(A[4,0],A[4,1],A[4,2],A[0,3],A[4,4]))
print('\n.\n.')

A = 

 8 10  8  2  2
 4  6  9  2  6
 8  4  4  2  7
 9  3  8  2  1
 7  3  3  2  6


 8 10  8  2  2
 4  6  9  2  6
 8  4  4  2  7
 9  3  8  2  1
 7  3  3  2  6

.
.


## Matrix B

In [15]:
print('B =')
print(colors.fg.blue)
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(B[0,0],B[0,1],B[0,2],B[0,3],B[0,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(B[1,0],B[1,1],B[1,2],B[1,3],B[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(B[2,0],B[2,1],B[2,2],B[2,3],B[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(B[3,0],B[3,1],B[3,2],B[3,3],B[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(B[4,0],B[4,1],B[4,2],B[4,3],B[4,4]))
print('\n')

B =

 3 10 10  4 10
 2  4 11  4  9
 7 11 11  3 10
 3  7 12  6 11
 9 11  9  8  6




## Matrix C

In [16]:
R1 = np.dot(A[0,:],B);
R2 = np.dot(A[1,:],B);
R3 = np.dot(A[2,:],B);
R4 = np.dot(A[3,:],B);
R5 = np.dot(A[4,:],B);

print("R[0,:]:");
print(colors.fg.purple);
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(R1[0],R1[1],R1[2],R1[3],R1[4]));
print(colors.reset);

print("R[1,:]:");
print(colors.fg.purple);
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(R2[0],R2[1],R2[2],R1[3],R2[4]));
print(colors.reset);

print("R[2,:]:");
print(colors.fg.purple);
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(R3[0],R3[1],R3[2],R3[3],R3[4]));
print(colors.reset);

print("R[3,:]:");
print(colors.fg.purple);
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(R4[0],R4[1],R4[2],R4[3],R4[4]));
print(colors.reset);

print("R[4,:]:");
print(colors.fg.purple);
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(R5[0],R5[1],R5[2],R5[3],R5[4]));
print(colors.reset);

print('C =')
print(colors.fg.purple)
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[0,0],C[0,1],C[0,2],C[0,3],C[0,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[1,0],C[1,1],C[1,2],C[0,3],C[1,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[2,0],C[2,1],C[2,2],C[0,3],C[2,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[3,0],C[3,1],C[3,2],C[0,3],C[3,4]))
print('{:2d} {:2d} {:2d} {:2d} {:2d}'.format(C[4,0],C[4,1],C[4,2],C[0,3],C[4,4]))

R[0,:]:

124 244 320 124 284

R[1,:]:

150 250 295 124 253

R[2,:]:

144 266 315 158 275

R[3,:]:

110 229 268 104 247

R[4,:]:

120 223 262 133 229

C =

124 244 320 124 284
150 250 295 124 253
144 266 315 124 275
110 229 268 124 247
120 223 262 124 229


# AB = Sum of (Cols of A) * (Rows of B)
4th Way: (M x 1)(1 x N) = Combation of either rows or cols

In [17]:
print(A[:,0:1])
print("")
print(B[0:1,:])
print("")
print(np.dot(A[:,0:1] , B[0:1,:]))

[[8]
 [4]
 [8]
 [9]
 [7]]

[[ 3 10 10  4 10]]

[[24 80 80 32 80]
 [12 40 40 16 40]
 [24 80 80 32 80]
 [27 90 90 36 90]
 [21 70 70 28 70]]


# Block Multipication
![recursivematrixmultiplication](https://user-images.githubusercontent.com/13907836/48246738-76615780-e3a5-11e8-8f9f-f5fb2b90936f.png)


In [18]:
A = np.random.randint(1,13,(20,20));
B = np.random.randint(1,13,(20,20));
print(A)
print("")
print(B)

[[ 4  7  6  3  5  4  2  1 11  3  1  6  1  6  9  9 10  5  1  3]
 [ 9  3 11  3  8  6 12  8  9  7  6 12  5  2 11 10  2  6  1 12]
 [ 7  6 10  6  2  3  2 12  5  6 10 10  2  9  3  7  1  9  7  8]
 [ 5  1 12  1  3  9  9 12  1  5 12  8 10  2  8  4  1  9  1  7]
 [ 2 10 11  4 10  7 12  5  6  9  1 12  8  6  5  2  9  3  6  3]
 [12  5  2  7  8  4  2 10  4 10  4  9  2 11 11  1  4  8  7  8]
 [ 2 12  9 11  4  8  4 12  4  7  7  1  3  5  2  9  7  7  8  1]
 [10  2 12  5  8 12  4 12 10  8  1  5  5 10 11  6  1  6 11  3]
 [10  7  8  1  1 11 10  2 11  8  2  6  1  5  5  7  6  2  4  9]
 [ 6  7  1  1 11  2  4  3  1  9  3 12 10  8  8  1  3 12  6 12]
 [12  6  6  6 11 12  1  6  1  6  8  7  8 10  9 12  8  1  4 12]
 [ 8  9  6  5  4  4  5 11  4  9  6  7  8 12 11 10  8  4  6 10]
 [ 2  3  3  2  8 12 11  3  4  2  7  6  3  6  7  4 10  6  2  4]
 [ 9 11 10  1  2  8  2 10  2  9  8 11  1  6  6  1  8  3 12  1]
 [ 5 10  5  6  7 10  5  2  8  6  8  1  2 12 11  7  3  8  9  7]
 [ 9  7  2  8 12  5  4  1  3  6 12 12  7  9 10  5  7  6

In [19]:
A_one_one = A[0:10,0:10]
A_one_two = A[0:10,10:20]

A_two_one = A[10:20,0:10]
A_two_two = A[0:10,10:20]

In [20]:
B_one_one = B[0:10,0:10]
B_one_two = B[0:10,10:20]

B_two_one = B[10:20,0:10]
B_two_two = B[10:20,10:20]

In [21]:
C_one_one = np.dot(A_one_one,B_one_one) + np.dot(A_one_two,B_two_one)
#C_one_two
#C_two_one
#C_two_two

print(C_one_one)

[[ 699  853  620  698  555  510  649  752  745  742]
 [ 923 1147 1024  979  748  913  995 1181  952 1134]
 [ 866  982  943  882  660  802  753 1014  899  943]
 [ 795  954  969  850  702  818  843  984  748  903]
 [ 819 1128  872  971  856  823  893  969  977  951]
 [ 967  985  929  809  634  757  730 1057  839  948]
 [ 836  984  884  904  786  787  803  952  918  802]
 [1078 1109 1085  966  783  884  903 1148 1018 1068]
 [ 773  899  806  808  631  803  825  973  850  970]
 [ 736  983  816  766  750  744  742  955  765  845]]


In [22]:
C = np.dot(A,B)
print(C[0:10 , 0:10])

[[ 699  853  620  698  555  510  649  752  745  742]
 [ 923 1147 1024  979  748  913  995 1181  952 1134]
 [ 866  982  943  882  660  802  753 1014  899  943]
 [ 795  954  969  850  702  818  843  984  748  903]
 [ 819 1128  872  971  856  823  893  969  977  951]
 [ 967  985  929  809  634  757  730 1057  839  948]
 [ 836  984  884  904  786  787  803  952  918  802]
 [1078 1109 1085  966  783  884  903 1148 1018 1068]
 [ 773  899  806  808  631  803  825  973  850  970]
 [ 736  983  816  766  750  744  742  955  765  845]]


# Inverse of Matrix
The inverse of A is A-1 only when A × A-1 = A-1 × A = I ( Therefore MAT(A) MUST be a Square matrix)


## Why Do We Need an Inverse?
Because with matrices we don't divide! Seriously, there is no concept of dividing by a matrix.

But we can multiply by an inverse, which achieves the same thing.

In [35]:
A = np.random.randint(1,2,(2,2));
print(A)
try:
    inverse = np.linalg.inv(A)
except np.linalg.LinAlgError:
    # Not invertible
    print("Not Inveritble");
else:
    # continue with what you were doing
    print("Inveritble");

[[1 1]
 [1 1]]
Not Inveritble
